FactoryGirl.define do
  factory :cable_run do
    site "MyString"
    building "MyString"
    room "MyString"
    drop "MyString"
    rdt "MyString"
    rdt_port "MyString"
    fdh_port "MyString"
    splitter "MyString"
    splitter_fiber "MyString"
    sheet
    pon_card "MyString"
    pon_port "MyString"
    fdh "MyString"
    notes "MyText"
    olt_rack "MyString"
    olt_chassis "MyString"
    vam_shelf "MyString"
    vam_module "MyString"
    vam_port "MyString"
    backbone_shelf "MyString"
    backbone_cable "MyString"
    backbone_port "MyString"
    fdh_location "MyString"
    rdt_location "MyString"
    ont_model "MyString"
    ont_sn "MyString"
    rdt_port_count "MyString"
    ont_ge_1_device "MyString"
    ont_ge_1_mac "MyString"
    ont_ge_2_device "MyString"
    ont_ge_2_mac "MyString"
    ont_ge_3_device "MyString"
    ont_ge_3_mac "MyString"
    ont_ge_4_device "MyString"
    ont_ge_4_mac "MyString"
  end

end
