# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f077ffded091b3701a1473d81fbb096069d9ab42be058824bbb2ce02061a9e32b7a028a9ee1000af890c2df2345525c1be871f1a07a757703f53f47132b8288f

test:
  secret_key_base: 0b20c5ad81177625930ac3043c16cf05c2703b5b8dc701a2419a0b669b0986823995e38af5a3bed68a8ed942f2f98d74bd3825dc68a54dabda2afbd102905b63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
